apiVersion: v1
kind: Pod
metadata:
  name: my-pod-env
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'echo $(APP_ENV) $(APP_DEBUG) && sleep 3600']
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_ENV
    - name: APP_DEBUG
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_DEBUG
  restartPolicy: Never