Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.name = "custom_docker_container"
    d.remains_running = false
    d.has_ssh = true
  end

  config.ssh.username = "vagrant"
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  config.vm.provision "shell", inline: <<-SHELL
    echo "Provisioning custom Docker container..."
  SHELL
end