apiVersion: v1
kind: Pod
metadata:
  name: my-pod-file-secret
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'cat /etc/secret-volume/username /etc/secret-volume/password && sleep 3600']
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  restartPolicy: Never