#cloud-config
users:
  - name: root
    ssh_authorized_keys:
      - YOUR PUBLIC SSH KEY
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - openssh-server
  - vim
  - curl
  - net-tools
  - git
  - mc
  - wget
  - fontconfig
  - openjdk-17-jre
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i 's/^PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - apt-get update
  - apt-get install jenkins -y
